In [74]:
##LOAD the data
import numpy as np
import pandas as pd
df=pd.read_csv("C:/Users/HP Core i5 10th Gen/Downloads//Finance_Ecommerce_Dirty_Dataset_csv.csv")

In [75]:
## inspect of the data set
# show the first 5 data
df.head()

,TransactionID,Date,AccountID,AccountName,TransactionType,Amount,Currency,ExchangeRate,Balance,Merchant,...,Subcategory,Country,City,PostalCode,CardNumber,Email,Phone,IsFraud,Notes,CustomerSince
0,TX103251,4/3/2025,AC3973,Arjun Sharma,Debit,47.36,USD,80.6864,-1714968.59,ShopEasy,...,Books,UK,Pune,153621.0,XXXX-XXXX-XXXX-4249,arjun.sharma@hotmail.com,-4.469492e+09,No,repeat purchase,16/09/2018
1,TX101874,10/8/2024,AC8970,Dev Kumar,Debit,159.55,inr,1.0000,-1162428.75,AutoZone,...,Concert,Australia,Delhi,380312.0,XXXX-XXXX-5979,dev.kumar@yahoo.com,5.882006e+09,No,cashback credited,11/7/2022
2,TX103746,9/14/2024,AC3777,Amit Gupta,Debit,2.43,GBP,102.0148,-2085783.34,BigBasket,...,Specialty,USA,Gurugram,NaN,XXXX-XXXX-2243,amit.gupta@example.com,8.832898e+08,No,cashback credited,Aug-21
3,TX105269,12/21/2024,AC9635,Ritu Roy,Refund,78.96,AED,18.1216,-2727243.49,ShopEasy,...,Restaurant,Australia,Mumbai,793747.0,XXXX-XXXX-9279,ritu.roy@hotmail.com,6.845400e+09,No,suspected fraud,2024
4,TX100463,4/14/2024,AC1329,Raj Bose,Refund,42.81,USD,78.4379,-259175.06,LocalMart,...,FastFood,USA,Mumbai,755067.0,NaN,raj.bose@hotmail.com,1.228611e+09,No,cashback credited,3/2/2023

In [76]:
## show the last dataset of 5
df.tail()

,TransactionID,Date,AccountID,AccountName,TransactionType,Amount,Currency,ExchangeRate,Balance,Merchant,...,Subcategory,Country,City,PostalCode,CardNumber,Email,Phone,IsFraud,Notes,CustomerSince
6055,TX105699,10/16/2023,AC5214,Vikram Iyer,Credit,69.09,USD,76.4757,"?-2,901,016.18",AutoZone,...,Hotel,UAE,Pune,856227.0,XXXX-XXXX-6489,vikram.iyer@yahoo.com,4.081945e+09,No,chargeback requested,2021
6056,TX102550,7/25/2025,AC8982,Anita Reddy,debit,4.94,USD,79.1632,-1557558.39,ShopEasy,...,Concert,Australia,Bengaluru,235120.0,XXXX-XXXX-5540,anita.reddy@gmail.com,2.586561e+09,No,monthly subscription,5/27/2023
6057,TX100537,9/24/2023,AC5308,Rohit Kumar,Credit,20.87,AED,19.7547,-276412.59,Amazon,...,Pharmacy,UAE,Mumbai,263866.0,XXXX-XXXX-XXXX-6774,rohit.kumar@hotmail.com,NaN,No,NaN,unknown
6058,TX101220,3/25/2024,AC7593,Sana Reddy,Credit,7.96,USD,76.8570,-593859.37,Reliance,...,Men,India,Hyderabad,152222.0,XXXX-XXXX-7745,sana.reddy@yahoo.com,6.866496e+09,No,manual adjustment,Aug-19
6059,TX104271,2/3/2025,AC4810,Neha Reddy,Credit,17.66,INR,1.0000,-2254562.37,ElectroWorld,...,Accessory,UK,Chennai,347582.0,XXXX-XXXX-XXXX-9831,neha.reddy@example.com,1.500553e+09,No,monthly subscription,20/06/2020

In [77]:
## the shape
df.shape

(6060, 23)

In [78]:
## the columns of the data
df.columns

Index(['TransactionID', 'Date', 'AccountID', 'AccountName', 'TransactionType',
       'Amount', 'Currency', 'ExchangeRate', 'Balance', 'Merchant',
       'MerchantPhone', 'MerchantEmail', 'Category', 'Subcategory', 'Country',
       'City', 'PostalCode', 'CardNumber', 'Email', 'Phone', 'IsFraud',
       'Notes', 'CustomerSince'],
      dtype='object')

In [79]:
## the datatypes 
df.dtypes

TransactionID       object
Date                object
AccountID           object
AccountName         object
TransactionType     object
Amount              object
Currency            object
ExchangeRate       float64
Balance             object
Merchant            object
MerchantPhone      float64
MerchantEmail       object
Category            object
Subcategory         object
Country             object
City                object
PostalCode         float64
CardNumber          object
Email               object
Phone              float64
IsFraud             object
Notes               object
CustomerSince       object
dtype: object

In [80]:
## the overall data information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6060 entries, 0 to 6059
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    6057 non-null   object
 1   Date             6060 non-null   object
 2   AccountID        6059 non-null   object
 3   AccountName      6059 non-null   object
 4   TransactionType  6058 non-null   object
 5   Amount           6059 non-null   object
 6   Currency         6055 non-null   object
 7   ExchangeRate     6058 non-null   float64
 8   Balance          5988 non-null   object
 9   Merchant         6058 non-null   object
 10  MerchantPhone    4647 non-null   float64
 11  MerchantEmail    4222 non-null   object
 12  Category         6058 non-null   object
 13  Subcategory      6055 non-null   object
 14  Country          6058 non-null   object
 15  City             6058 non-null   object
 16  PostalCode       5742 non-null   float64
 17  CardNumber       5621 non-null   object
 18  Email            5801 non-null   object
 19  Phone            5732 non-null   float64
 20  IsFraud          5984 non-null   object
 21  Notes            5256 non-null   object
 22  CustomerSince    6058 non-null   object
dtypes: float64(4), object(19)
memory usage: 1.1+ MB

In [81]:
## the statistical overview of the data
df.describe()

       ExchangeRate  MerchantPhone     PostalCode         Phone
count   6058.000000   4.647000e+03    5742.000000  5.732000e+03
mean      46.319508   3.094016e+09  534220.496517  2.977499e+09
std       40.254595   4.852691e+09  274401.478310  4.946857e+09
min        1.000000  -9.981343e+09     102.000000 -9.985638e+09
25%        1.000000   7.206737e+08  299628.500000  6.050150e+08
50%       72.091800   3.827888e+09  538097.500000  3.779223e+09
75%       80.274425   6.838675e+09  775529.500000  6.829491e+09
max      109.968400   9.999725e+09  999962.000000  9.999725e+09

In [82]:
##clean the columns name
df.columns=df.columns.str.strip().str.lower().str.replace("","",regex=True)

In [83]:
## handle the duplicated
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6055    False
6056    False
6057    False
6058    False
6059    False
Length: 6060, dtype: bool

In [84]:
##count the duplicated 
df.duplicated().sum()

np.int64(1)

In [85]:
## remove the duplicated
df.drop_duplicates(inplace=True)

In [86]:
##count the duplicated 
df.duplicated().sum()

np.int64(0)

In [87]:
##handle missing value
df.isnull().sum()

transactionid         3
date                  0
accountid             1
accountname           1
transactiontype       2
amount                1
currency              5
exchangerate          2
balance              72
merchant              2
merchantphone      1413
merchantemail      1837
category              2
subcategory           5
country               2
city                  2
postalcode          318
cardnumber          439
email               259
phone               328
isfraud              76
notes               804
customersince         2
dtype: int64

In [88]:
## the total missing value
df.isnull().sum().sum()

np.int64(5576)

In [89]:
## change the data types
df['amount']=pd.to_numeric(df['amount'],errors='coerce')
df['amount'].dtype
df['amount']

0        47.36
1       159.55
2         2.43
3        78.96
4        42.81
         ...
6055     69.09
6056      4.94
6057     20.87
6058      7.96
6059     17.66
Name: amount, Length: 6059, dtype: float64

In [90]:
## change the data types
df['amount']=pd.to_numeric(df['exchangerate'],errors='coerce')
df['exchangerate'].dtype
df['amount']

0        80.6864
1         1.0000
2       102.0148
3        18.1216
4        78.4379
          ...
6055     76.4757
6056     79.1632
6057     19.7547
6058     76.8570
6059      1.0000
Name: amount, Length: 6059, dtype: float64

In [91]:
## change the data types
df['balance']=pd.to_numeric(df['balance'],errors='coerce')
df['balance']

0      -1714968.59
1      -1162428.75
2      -2085783.34
3      -2727243.49
4       -259175.06
           ...
6055           NaN
6056   -1557558.39
6057    -276412.59
6058    -593859.37
6059   -2254562.37
Name: balance, Length: 6059, dtype: float64

In [92]:
## change the string datatype
df['postalcode']=df['postalcode'].astype(str).str.replace('.0','',regex=False)
df['postalcode']

0       153621
1       380312
2          nan
3       793747
4       755067
         ...
6055    856227
6056    235120
6057    263866
6058    152222
6059    347582
Name: postalcode, Length: 6059, dtype: object

In [93]:
## change the string datatype
df['phone']=df['phone'].astype(str).str.replace('.0','',regex=False)
df['phone']

0       -4469491713
1        5882006077
2         883289751
3        6845399861
4        1228611124
           ...
6055     4081945405
6056     2586560860
6057            nan
6058     6866495890
6059     1500552888
Name: phone, Length: 6059, dtype: object

In [94]:
## change the string datatype
df['phone']=df['phone'].astype(str).str.replace('.0','',regex=False)
df['phone']

0       -4469491713
1        5882006077
2         883289751
3        6845399861
4        1228611124
           ...
6055     4081945405
6056     2586560860
6057            nan
6058     6866495890
6059     1500552888
Name: phone, Length: 6059, dtype: object

In [95]:
## change the string datatype
df['merchantphone']=df['merchantphone'].astype(str)
df['merchantphone']

0                nan
1       1856170186.0
2        323250652.0
3                nan
4        676286112.0
            ...
6055    9858342457.0
6056    3522591006.0
6057    7629143650.0
6058    2329283285.0
6059    3642495923.0
Name: merchantphone, Length: 6059, dtype: object

In [96]:
## the handle the date columns
df['date']=pd.to_datetime(df['date'],errors='coerce')
df['date']

0      2025-04-03
1      2024-10-08
2      2024-09-14
3      2024-12-21
4      2024-04-14
          ...
6055   2023-10-16
6056   2025-07-25
6057   2023-09-24
6058   2024-03-25
6059   2025-02-03
Name: date, Length: 6059, dtype: datetime64[ns]

In [97]:
## convert the datetimes
df['customersince']=pd.to_datetime(df['customersince'],format="mixed",errors='coerce')
df['customersince']

0      2018-09-16
1      2022-11-07
2             NaT
3      2024-01-01
4      2023-03-02
          ...
6055   2021-01-01
6056   2023-05-27
6057          NaT
6058          NaT
6059   2020-06-20
Name: customersince, Length: 6059, dtype: datetime64[ns]

In [98]:
df['customersince'].isnull().sum().sum()

np.int64(1625)

In [99]:
## show the few data
df['customersince'].head(10)

0   2018-09-16
1   2022-11-07
2          NaT
3   2024-01-01
4   2023-03-02
5   2015-11-24
6   2025-08-08
7   2021-02-20
8          NaT
9          NaT
Name: customersince, dtype: datetime64[ns]

In [100]:
## missing value fillup by the median
df['amount']=df['amount'].fillna(df['amount'].median())
df['amount']

0        80.6864
1         1.0000
2       102.0148
3        18.1216
4        78.4379
          ...
6055     76.4757
6056     79.1632
6057     19.7547
6058     76.8570
6059      1.0000
Name: amount, Length: 6059, dtype: float64

In [101]:
## missing value fillup by the median
df['balance']=df['balance'].fillna(df['balance'].median())
df['balance']

0      -1714968.590
1      -1162428.750
2      -2085783.340
3      -2727243.490
4       -259175.060
           ...
6055   -1641946.095
6056   -1557558.390
6057    -276412.590
6058    -593859.370
6059   -2254562.370
Name: balance, Length: 6059, dtype: float64

In [102]:
## missing value fillup by the median
df['exchangerate']=df['exchangerate'].fillna(df['exchangerate'].median())
df['exchangerate']

0        80.6864
1         1.0000
2       102.0148
3        18.1216
4        78.4379
          ...
6055     76.4757
6056     79.1632
6057     19.7547
6058     76.8570
6059      1.0000
Name: exchangerate, Length: 6059, dtype: float64

In [103]:
## categorical value fillup by  mode
cols = ['transactiontype','currency','category','subcategory','country','city']

print("Before filling:")
print(df[cols].isnull().sum())

for categ in cols:
    df[categ] = df[categ].fillna(df[categ].mode()[0])

print("\nAfter filling:")
print(df[cols].isnull().sum())

Before filling:
transactiontype    2
currency           5
category           2
subcategory        5
country            2
city               2
dtype: int64

After filling:
transactiontype    0
currency           0
category           0
subcategory        0
country            0
city               0
dtype: int64

In [104]:
df.isnull().sum()

transactionid         3
date                  0
accountid             1
accountname           1
transactiontype       0
amount                0
currency              0
exchangerate          0
balance               0
merchant              2
merchantphone         0
merchantemail      1837
category              0
subcategory           0
country               0
city                  0
postalcode            0
cardnumber          439
email               259
phone                 0
isfraud              76
notes               804
customersince      1625
dtype: int64

In [105]:
## drop the nan of the ID 
df=df.dropna(subset=['transactionid','accountid','accountname'])
df

,transactionid,date,accountid,accountname,transactiontype,amount,currency,exchangerate,balance,merchant,...,subcategory,country,city,postalcode,cardnumber,email,phone,isfraud,notes,customersince
0,TX103251,2025-04-03,AC3973,Arjun Sharma,Debit,80.6864,USD,80.6864,-1714968.590,ShopEasy,...,Books,UK,Pune,153621,XXXX-XXXX-XXXX-4249,arjun.sharma@hotmail.com,-4469491713,No,repeat purchase,2018-09-16
1,TX101874,2024-10-08,AC8970,Dev Kumar,Debit,1.0000,inr,1.0000,-1162428.750,AutoZone,...,Concert,Australia,Delhi,380312,XXXX-XXXX-5979,dev.kumar@yahoo.com,5882006077,No,cashback credited,2022-11-07
2,TX103746,2024-09-14,AC3777,Amit Gupta,Debit,102.0148,GBP,102.0148,-2085783.340,BigBasket,...,Specialty,USA,Gurugram,nan,XXXX-XXXX-2243,amit.gupta@example.com,883289751,No,cashback credited,NaT
3,TX105269,2024-12-21,AC9635,Ritu Roy,Refund,18.1216,AED,18.1216,-2727243.490,ShopEasy,...,Restaurant,Australia,Mumbai,793747,XXXX-XXXX-9279,ritu.roy@hotmail.com,6845399861,No,suspected fraud,2024-01-01
4,TX100463,2024-04-14,AC1329,Raj Bose,Refund,78.4379,USD,78.4379,-259175.060,LocalMart,...,FastFood,USA,Mumbai,755067,NaN,raj.bose@hotmail.com,1228611124,No,cashback credited,2023-03-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6055,TX105699,2023-10-16,AC5214,Vikram Iyer,Credit,76.4757,USD,76.4757,-1641946.095,AutoZone,...,Hotel,UAE,Pune,856227,XXXX-XXXX-6489,vikram.iyer@yahoo.com,4081945405,No,chargeback requested,2021-01-01
6056,TX102550,2025-07-25,AC8982,Anita Reddy,debit,79.1632,USD,79.1632,-1557558.390,ShopEasy,...,Concert,Australia,Bengaluru,235120,XXXX-XXXX-5540,anita.reddy@gmail.com,2586560860,No,monthly subscription,2023-05-27
6057,TX100537,2023-09-24,AC5308,Rohit Kumar,Credit,19.7547,AED,19.7547,-276412.590,Amazon,...,Pharmacy,UAE,Mumbai,263866,XXXX-XXXX-XXXX-6774,rohit.kumar@hotmail.com,nan,No,NaN,NaT
6058,TX101220,2024-03-25,AC7593,Sana Reddy,Credit,76.8570,USD,76.8570,-593859.370,Reliance,...,Men,India,Hyderabad,152222,XXXX-XXXX-7745,sana.reddy@yahoo.com,6866495890,No,manual adjustment,NaT
6059,TX104271,2025-02-03,AC4810,Neha Reddy,Credit,1.0000,INR,1.0000,-2254562.370,ElectroWorld,...,Accessory,UK,Chennai,347582,XXXX-XXXX-XXXX-9831,neha.reddy@example.com,1500552888,No,monthly subscription,2020-06-20

In [106]:
## text columns misssing fillup
df['notes']=df['notes'].fillna('No Notes')
df['notes']

0            repeat purchase
1          cashback credited
2          cashback credited
3            suspected fraud
4          cashback credited
                ...
6055    chargeback requested
6056    monthly subscription
6057                No Notes
6058       manual adjustment
6059    monthly subscription
Name: notes, Length: 6055, dtype: object

In [107]:
## fillup by 0
df['isfraud']=df['isfraud'].fillna(0)
df['isfraud']

0       No
1       No
2       No
3       No
4       No
        ..
6055    No
6056    No
6057    No
6058    No
6059    No
Name: isfraud, Length: 6055, dtype: object

In [108]:
df.columns

Index(['transactionid', 'date', 'accountid', 'accountname', 'transactiontype',
       'amount', 'currency', 'exchangerate', 'balance', 'merchant',
       'merchantphone', 'merchantemail', 'category', 'subcategory', 'country',
       'city', 'postalcode', 'cardnumber', 'email', 'phone', 'isfraud',
       'notes', 'customersince'],
      dtype='object')

In [109]:
## missing value fillup by the unknown
num=['postalcode','phone','email','merchantemail','merchantemail','merchantphone','cardnumber']
print("sum of missing value:")
print(df[num].isnull().sum())

for e in num:
    df[e]=df[e].fillna('Unknown')
print('\n After filling:')
print(df[e].isnull().sum())

sum of missing value:
postalcode          0
phone               0
email             257
merchantemail    1834
merchantemail    1834
merchantphone       0
cardnumber        438
dtype: int64

 After filling:
0

In [110]:
## nan value fillup by mode
df['postalcode'] = df['postalcode'].astype(str).replace('nan', np.nan)
df['postalcode'] = df['postalcode'].fillna(df['postalcode'].mode()[0])
df['postalcode']

0       153621
1       380312
2          851
3       793747
4       755067
         ...
6055    856227
6056    235120
6057    263866
6058    152222
6059    347582
Name: postalcode, Length: 6055, dtype: object

In [111]:
## fillup by the mode
df['phone']=df['phone'].astype(str).replace('nan',np.nan)
df['phone']=df['phone'].fillna(df['phone'].mode()[0])
df['phone']

0       -4469491713
1        5882006077
2         883289751
3        6845399861
4        1228611124
           ...
6055     4081945405
6056     2586560860
6057    -1162887189
6058     6866495890
6059     1500552888
Name: phone, Length: 6055, dtype: object

In [112]:
df['phone'] = df['phone'].astype(str).str.replace('-', '', regex=False)
df['phone']

0       4469491713
1       5882006077
2        883289751
3       6845399861
4       1228611124
           ...
6055    4081945405
6056    2586560860
6057    1162887189
6058    6866495890
6059    1500552888
Name: phone, Length: 6055, dtype: object

In [113]:
df.head(23)

,transactionid,date,accountid,accountname,transactiontype,amount,currency,exchangerate,balance,merchant,...,subcategory,country,city,postalcode,cardnumber,email,phone,isfraud,notes,customersince
0,TX103251,2025-04-03,AC3973,Arjun Sharma,Debit,80.6864,USD,80.6864,-1714968.590,ShopEasy,...,Books,UK,Pune,153621,XXXX-XXXX-XXXX-4249,arjun.sharma@hotmail.com,4469491713,No,repeat purchase,2018-09-16
1,TX101874,2024-10-08,AC8970,Dev Kumar,Debit,1.0000,inr,1.0000,-1162428.750,AutoZone,...,Concert,Australia,Delhi,380312,XXXX-XXXX-5979,dev.kumar@yahoo.com,5882006077,No,cashback credited,2022-11-07
2,TX103746,2024-09-14,AC3777,Amit Gupta,Debit,102.0148,GBP,102.0148,-2085783.340,BigBasket,...,Specialty,USA,Gurugram,851,XXXX-XXXX-2243,amit.gupta@example.com,883289751,No,cashback credited,NaT
3,TX105269,2024-12-21,AC9635,Ritu Roy,Refund,18.1216,AED,18.1216,-2727243.490,ShopEasy,...,Restaurant,Australia,Mumbai,793747,XXXX-XXXX-9279,ritu.roy@hotmail.com,6845399861,No,suspected fraud,2024-01-01
4,TX100463,2024-04-14,AC1329,Raj Bose,Refund,78.4379,USD,78.4379,-259175.060,LocalMart,...,FastFood,USA,Mumbai,755067,Unknown,raj.bose@hotmail.com,1228611124,No,cashback credited,2023-03-02
5,TX105222,2025-05-20,AC4567,Maya Patel,Refund,1.0000,INR,1.0000,-2681033.190,Amazon,...,Electricity,India,Hyderabad,915819,XXXX-XXXX-4011,maya.patel@example.com,7629416248,No,No Notes,2015-11-24
6,TX101095,2023-09-14,AC1401,Dev Iyer,Credit,80.9396,USD,80.9396,-1641946.095,Starbucks,...,Electricity,India,Jaipur,880938,XXXX-XXXX-9517,dev.iyer@example.com,1162887189,No,manual adjustment,2025-08-08
7,TX104232,2023-10-23,AC3573,Priya Mehta,CREDIT,1.0000,INR,1.0000,-2238462.320,AutoZone,...,Flight,UAE,Mumbai,267413,XXXX-XXXX-3629,priya.mehta@example.com,8044301765,No,No Notes,2021-02-20
8,TX103255,2023-10-31,AC7007,Neha Roy,Refund,109.7276,GBP,109.7276,-1773994.740,Myntra,...,Fuel,UK,Jaipur,326900,XXXX-XXXX-XXXX-2630,neha.roy@hotmail.com,5473229213,No,manual adjustment,NaT
9,TX100757,2024-02-07,AC1584,Priya Reddy,Refund,82.6800,USD,82.6800,-445835.540,Reliance,...,Clinic,UK,Pune,135022,Unknown,priya.reddy@hotmail.com,1776923306,No,repeat purchase,NaT
10,TX101935,2024-07-08,AC5372,Raj Reddy,Debit,96.0691,GBP,96.0691,-1168892.390,ShopEasy,...,Fuel,USA,Gurugram,350578,XXXX-XXXX-9667,raj.reddy@yahoo.com,6454843768,No,monthly subscription,2017-01-01
11,TX104361,2024-10-13,AC4603,Raj Kumar,Refund,1.0000,INR,1.0000,-2419825.460,Zomato,...,Books,UK,Noida,943828,XXXX-XXXX-XXXX-3858,raj.kumar@gmail.com,7960179727,No,promo applied,NaT
12,TX105135,2023-11-01,AC1978,Dev Bose,Debit,19.8767,AED,19.8767,-2678063.640,Flipkart,...,Concert,USA,Mumbai,541596,XXXX-XXXX-XXXX-7809,dev.bose@yahoo.com,5771717716,No,repeat purchase,NaT
13,TX102862,2025-02-24,AC6736,suresh ROY,CREDIT,20.5500,AED,20.5500,-1626685.130,Paytm Mall,...,Restaurant,Canada,Pune,363091,XXXX-XXXX-5376,Unknown,5856285767,No,repeat purchase,2015-08-03
14,TX100059,2024-05-03,AC7201,Lina Chopra,Credit,1.0000,INR,1.0000,-144093.870,Walmart,...,Fuel,India,Delhi,569390,XXXX-XXXX-3817,lina.chopra@gmail.com,2148585218,No,repeat purchase,2018-01-01
15,TX101306,2024-08-25,AC3643,Sana Kumar,Credit,81.3081,USD,81.3081,-965108.080,Starbucks,...,Streaming,Canada,Bengaluru,313942,XXXX-XXXX-1286,sana.kumar@yahoo.com,8285425328,No,chargeback requested,2025-01-01
16,TX105440,2024-09-12,AC3521,Asha Das,debit,80.4133,USD,80.4133,-2783810.240,ShopEasy,...,Supermarket,UK,Jaipur,244894,4.81928E+15,asha.das@gmail.com,2421026890,No,repeat purchase,2023-01-01
17,TX104539,2025-06-20,AC3852,Suresh Khan,debit,1.0000,INRr,1.0000,-2464156.500,Zomato,...,Internet,UK,Jaipur,639702,XXXX-XXXX-XXXX-4331,suresh.khan@example.com,9297816406,No,suspected fraud,2017-05-12
18,TX104915,2024-10-10,AC9262,Lina Khan,Debit,76.2602,USD,76.2602,-1641946.095,ElectroWorld,...,Repair,UK,Jaipur,418828,XXXX-XXXX-XXXX-9478,lina.khan@yahoo.com,5630209429,No,cashback credited,2021-09-23
19,TX105847,2024-05-10,AC4073,Raj Sharma,debit,1.0000,INR,1.0000,-1641946.095,BigBasket,...,Course,India,Mumbai,943210,XXXX-XXXX-XXXX-4864,raj.sharma@yahoo.com,4272682811,No,monthly subscription,2022-03-17
20,TX104626,2024-11-14,AC2149,Asha Bose,CREDIT,21.1947,AED,21.1947,-2466729.790,Myntra,...,Laptop,Canada,Mumbai,218025,XXXX-XXXX-XXXX-1963,asha.bose@hotmail.com,2848087356,No,chargeback requested,2020-01-01
21,TX101715,2024-12-14,AC4305,Dev Chopra,Refund,92.4582,GBP,92.4582,-1641946.095,Myntra,...,Concert,USA,Hyderabad,554639,XXXX-XXXX-8772,dev.chopra@yahoo.com,9782333274,No,chargeback requested,2015-01-01
22,TX100452,2025-05-16,AC6768,Rohit Kumar,Debit,80.4977,USD,80.4977,-1641946.095,BigBasket,...,Concert,UK,Chennai,143661,XXXX-XXXX-3040,rohit.kumar@hotmail.com,2303906802,No,monthly subscription,2024-03-04

In [114]:
df['customersince'].isnull().sum()

np.int64(1623)

In [115]:
# Backup
df['customersince_raw'] = df['customersince']

# Convert mixed dates
df['customersince'] = pd.to_datetime(
    df['customersince'],
    format='mixed',
    errors='coerce'
)

# Fill from same customer
df['customersince'] = (
    df.groupby('accountid')['customersince']
      .transform(lambda x: x.ffill().bfill())
)

# Check remaining missing
print(df['customersince'].isna().sum())

970

In [116]:
## fillup missing
df['customersince'] = df['customersince'].fillna(
    df.groupby('accountid')['date'].transform('min')
)

print(df['customersince'].isnull().sum())

0

In [117]:
df['cdustomersince'] = df['customersince'].fillna(df['customersince'].median())
df['cdustomersince']

0      2018-09-16
1      2022-11-07
2      2015-06-23
3      2024-01-01
4      2023-03-02
          ...
6055   2021-01-01
6056   2023-05-27
6057   2023-09-24
6058   2020-10-14
6059   2020-06-20
Name: cdustomersince, Length: 6055, dtype: datetime64[ns]

In [118]:
# remove everythong withouut nunber,point and negative
df['amount'] = df['amount'].astype(str).str.replace(r'[^0-9.\-]', '', regex=True)

# replace by nan
df['amount'] = df['amount'].replace('', np.nan)

# numeric  convert
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

print(df['amount'].isnull().sum())
print(df['amount'].describe())

0
count    6055.000000
mean       46.350446
std        40.251934
min         1.000000
25%         1.000000
50%        72.101700
75%        80.276450
max       109.968400
Name: amount, dtype: float64

In [119]:
df['balance'] = df['balance'].astype(str).str.replace(r'[^0-9.\-]', '', regex=True)
df['balance'] = pd.to_numeric(df['balance'], errors='coerce')
df['balance'] = df['balance'].abs()  # All negative
df['balance']

0       1714968.590
1       1162428.750
2       2085783.340
3       2727243.490
4        259175.060
           ...
6055    1641946.095
6056    1557558.390
6057     276412.590
6058     593859.370
6059    2254562.370
Name: balance, Length: 6055, dtype: float64

In [120]:
##show the columns 
df.columns

Index(['transactionid', 'date', 'accountid', 'accountname', 'transactiontype',
       'amount', 'currency', 'exchangerate', 'balance', 'merchant',
       'merchantphone', 'merchantemail', 'category', 'subcategory', 'country',
       'city', 'postalcode', 'cardnumber', 'email', 'phone', 'isfraud',
       'notes', 'customersince', 'customersince_raw', 'cdustomersince'],
      dtype='object')

In [121]:
## drop the columns
df = df.drop(columns=['customersince_raw', 'cdustomersince'])

In [122]:
df.dtypes

transactionid              object
date               datetime64[ns]
accountid                  object
accountname                object
transactiontype            object
amount                    float64
currency                   object
exchangerate              float64
balance                   float64
merchant                   object
merchantphone              object
merchantemail              object
category                   object
subcategory                object
country                    object
city                       object
postalcode                 object
cardnumber                 object
email                      object
phone                      object
isfraud                    object
notes                      object
customersince      datetime64[ns]
dtype: object

In [123]:
df.head()

,transactionid,date,accountid,accountname,transactiontype,amount,currency,exchangerate,balance,merchant,...,subcategory,country,city,postalcode,cardnumber,email,phone,isfraud,notes,customersince
0,TX103251,2025-04-03,AC3973,Arjun Sharma,Debit,80.6864,USD,80.6864,1714968.59,ShopEasy,...,Books,UK,Pune,153621,XXXX-XXXX-XXXX-4249,arjun.sharma@hotmail.com,4469491713,No,repeat purchase,2018-09-16
1,TX101874,2024-10-08,AC8970,Dev Kumar,Debit,1.0000,inr,1.0000,1162428.75,AutoZone,...,Concert,Australia,Delhi,380312,XXXX-XXXX-5979,dev.kumar@yahoo.com,5882006077,No,cashback credited,2022-11-07
2,TX103746,2024-09-14,AC3777,Amit Gupta,Debit,102.0148,GBP,102.0148,2085783.34,BigBasket,...,Specialty,USA,Gurugram,851,XXXX-XXXX-2243,amit.gupta@example.com,883289751,No,cashback credited,2015-06-23
3,TX105269,2024-12-21,AC9635,Ritu Roy,Refund,18.1216,AED,18.1216,2727243.49,ShopEasy,...,Restaurant,Australia,Mumbai,793747,XXXX-XXXX-9279,ritu.roy@hotmail.com,6845399861,No,suspected fraud,2024-01-01
4,TX100463,2024-04-14,AC1329,Raj Bose,Refund,78.4379,USD,78.4379,259175.06,LocalMart,...,FastFood,USA,Mumbai,755067,Unknown,raj.bose@hotmail.com,1228611124,No,cashback credited,2023-03-02

In [124]:
df['currency'].unique()

array(['USD ', 'inr', 'GBP', 'AED', 'USD', 'INR', 'INRr', 'usd', 'INR ',
       'gbp', 'aed', 'AED ', 'GBP ', 'usd '], dtype=object)

In [125]:
## THE CURRENCY CHANGE OF FORMAT
df['currency']=df['currency'].str.upper().str.strip()
df['currency']=df['currency'].replace({'INRR':'INR'})
df['currency'].head(10)

0    USD
1    INR
2    GBP
3    AED
4    USD
5    INR
6    USD
7    INR
8    GBP
9    USD
Name: currency, dtype: object

In [126]:
##the drop of the Merchant_Phone
df=df.drop(columns='merchantphone')
df

,transactionid,date,accountid,accountname,transactiontype,amount,currency,exchangerate,balance,merchant,...,subcategory,country,city,postalcode,cardnumber,email,phone,isfraud,notes,customersince
0,TX103251,2025-04-03,AC3973,Arjun Sharma,Debit,80.6864,USD,80.6864,1714968.590,ShopEasy,...,Books,UK,Pune,153621,XXXX-XXXX-XXXX-4249,arjun.sharma@hotmail.com,4469491713,No,repeat purchase,2018-09-16
1,TX101874,2024-10-08,AC8970,Dev Kumar,Debit,1.0000,INR,1.0000,1162428.750,AutoZone,...,Concert,Australia,Delhi,380312,XXXX-XXXX-5979,dev.kumar@yahoo.com,5882006077,No,cashback credited,2022-11-07
2,TX103746,2024-09-14,AC3777,Amit Gupta,Debit,102.0148,GBP,102.0148,2085783.340,BigBasket,...,Specialty,USA,Gurugram,851,XXXX-XXXX-2243,amit.gupta@example.com,883289751,No,cashback credited,2015-06-23
3,TX105269,2024-12-21,AC9635,Ritu Roy,Refund,18.1216,AED,18.1216,2727243.490,ShopEasy,...,Restaurant,Australia,Mumbai,793747,XXXX-XXXX-9279,ritu.roy@hotmail.com,6845399861,No,suspected fraud,2024-01-01
4,TX100463,2024-04-14,AC1329,Raj Bose,Refund,78.4379,USD,78.4379,259175.060,LocalMart,...,FastFood,USA,Mumbai,755067,Unknown,raj.bose@hotmail.com,1228611124,No,cashback credited,2023-03-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6055,TX105699,2023-10-16,AC5214,Vikram Iyer,Credit,76.4757,USD,76.4757,1641946.095,AutoZone,...,Hotel,UAE,Pune,856227,XXXX-XXXX-6489,vikram.iyer@yahoo.com,4081945405,No,chargeback requested,2021-01-01
6056,TX102550,2025-07-25,AC8982,Anita Reddy,debit,79.1632,USD,79.1632,1557558.390,ShopEasy,...,Concert,Australia,Bengaluru,235120,XXXX-XXXX-5540,anita.reddy@gmail.com,2586560860,No,monthly subscription,2023-05-27
6057,TX100537,2023-09-24,AC5308,Rohit Kumar,Credit,19.7547,AED,19.7547,276412.590,Amazon,...,Pharmacy,UAE,Mumbai,263866,XXXX-XXXX-XXXX-6774,rohit.kumar@hotmail.com,1162887189,No,No Notes,2023-09-24
6058,TX101220,2024-03-25,AC7593,Sana Reddy,Credit,76.8570,USD,76.8570,593859.370,Reliance,...,Men,India,Hyderabad,152222,XXXX-XXXX-7745,sana.reddy@yahoo.com,6866495890,No,manual adjustment,2020-10-14
6059,TX104271,2025-02-03,AC4810,Neha Reddy,Credit,1.0000,INR,1.0000,2254562.370,ElectroWorld,...,Accessory,UK,Chennai,347582,XXXX-XXXX-XXXX-9831,neha.reddy@example.com,1500552888,No,monthly subscription,2020-06-20

In [127]:
## the outliers detection
df.columns

Index(['transactionid', 'date', 'accountid', 'accountname', 'transactiontype',
       'amount', 'currency', 'exchangerate', 'balance', 'merchant',
       'merchantemail', 'category', 'subcategory', 'country', 'city',
       'postalcode', 'cardnumber', 'email', 'phone', 'isfraud', 'notes',
       'customersince'],
      dtype='object')

In [128]:
## the outlier check
numeric_cols = [
    'amount',
    'exchangerate',
    'balance'
]
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print(f'{col}: {len(outliers)} outliers')

amount: 0 outliers
exchangerate: 0 outliers
balance: 0 outliers

In [129]:
## the check of amount 
(df['amount'] < 0).sum()

np.int64(0)

In [130]:
## the check of exchange rage
df[df['exchangerate']<=0]

Empty DataFrame
Columns: [transactionid, date, accountid, accountname, transactiontype, amount, currency, exchangerate, balance, merchant, merchantemail, category, subcategory, country, city, postalcode, cardnumber, email, phone, isfraud, notes, customersince]
Index: []

[0 rows x 22 columns]

In [131]:
## the check of balance
df[df['balance']<0]

Empty DataFrame
Columns: [transactionid, date, accountid, accountname, transactiontype, amount, currency, exchangerate, balance, merchant, merchantemail, category, subcategory, country, city, postalcode, cardnumber, email, phone, isfraud, notes, customersince]
Index: []

[0 rows x 22 columns]

In [132]:
## the check  of the date before customersince
df[df['date']<df['customersince']]

,transactionid,date,accountid,accountname,transactiontype,amount,currency,exchangerate,balance,merchant,...,subcategory,country,city,postalcode,cardnumber,email,phone,isfraud,notes,customersince
6,TX101095,2023-09-14,AC1401,Dev Iyer,Credit,80.9396,USD,80.9396,1641946.095,Starbucks,...,Electricity,India,Jaipur,880938,XXXX-XXXX-9517,dev.iyer@example.com,1162887189,No,manual adjustment,2025-08-08
8,TX103255,2023-10-31,AC7007,Neha Roy,Refund,109.7276,GBP,109.7276,1773994.740,Myntra,...,Fuel,UK,Jaipur,326900,XXXX-XXXX-XXXX-2630,neha.roy@hotmail.com,5473229213,No,manual adjustment,2024-01-01
15,TX101306,2024-08-25,AC3643,Sana Kumar,Credit,81.3081,USD,81.3081,965108.080,Starbucks,...,Streaming,Canada,Bengaluru,313942,XXXX-XXXX-1286,sana.kumar@yahoo.com,8285425328,No,chargeback requested,2025-01-01
39,TX104242,2023-12-09,AC9059,Dev Joshi,Refund,78.6113,USD,78.6113,1641946.095,ShopEasy,...,Men,USA,Mumbai,163619,XXXX-XXXX-7597,dev.joshi@gmail.com,5703662729,No,promo applied,2025-09-11
42,TX101172,2023-10-31,AC2103,Uma Chopra,Debit,1.0000,INR,1.0000,558165.120,Zomato,...,Streaming,UK,Hyderabad,601894,XXXX-XXXX-6321,uma.chopra@gmail.com,5898306104,No,repeat purchase,2026-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6019,TX105040,2025-06-23,AC2261,Priya Reddy,CREDIT,75.4656,USD,75.4656,1641946.095,Myntra,...,Men,India,Mumbai,257840,XXXX-XXXX-XXXX-5143,priya.reddy@example.com,5656999544,No,repeat purchase,2025-09-23
6022,TX100772,2023-12-28,AC1480,Priya Singh,Refund,1.0000,INR,1.0000,1641946.095,Myntra,...,Supermarket,USA,Chennai,757942,XXXX-XXXX-7480,priya.singh@hotmail.com,3853313772,No,promo applied -- verify\ncontact support,2024-01-01
6031,TX103896,2023-09-15,AC1720,Arjun Gupta,Refund,79.9761,USD,79.9761,2119919.500,Zomato,...,Repair,Canada,Kolkata,675366,XXXX-XXXX-XXXX-1606,arjun.gupta@gmail.com,2088996068,No,chargeback requested,2026-01-01
6042,TX101092,2025-02-08,AC6022,Suresh Mehta,CREDIT,72.5685,USD,72.5685,554566.580,ShopEasy,...,Restaurant,UK,Bengaluru,404263,XXXX-XXXX-9141,suresh.mehta@example.com,4096680112,No,monthly subscription,2025-09-05
6051,TX101372,2024-08-17,AC2579,Rohit Nair,Credit,21.5274,AED,21.5274,974547.020,Reliance,...,Accessory,UK,Pune,786139,XXXX-XXXX-XXXX-7912,rohit.nair@gmail.com,1162887189,No,suspected fraud,2025-03-09

In [133]:
df['isfraud']=df['isfraud'].replace({
    0:'No','Yess':'Yes'})
df['isfraud'].unique()

array(['No', 'Yes'], dtype=object)

In [134]:
## the validation of the data
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (6055, 22)

Missing values:
transactionid      0
date               0
accountid          0
accountname        0
transactiontype    0
amount             0
currency           0
exchangerate       0
balance            0
merchant           1
merchantemail      0
category           0
subcategory        0
country            0
city               0
postalcode         0
cardnumber         0
email              0
phone              0
isfraud            0
notes              0
customersince      0
dtype: int64

Duplicates:
0

Data types:
transactionid              object
date               datetime64[ns]
accountid                  object
accountname                object
transactiontype            object
amount                    float64
currency                   object
exchangerate              float64
balance                   float64
merchant                   object
merchantemail              object
category                   object
subcategory                object
country                    object
city                       object
postalcode                 object
cardnumber                 object
email                      object
phone                      object
isfraud                    object
notes                      object
customersince      datetime64[ns]
dtype: object

In [135]:
## the statistical overview of the data
df.describe()

,date,amount,exchangerate,balance,customersince
count,6055,6055.000000,6055.000000,6.055000e+03,6055
mean,2024-09-16 00:34:14.764657408,46.350446,46.350446,1.633511e+06,2021-03-23 14:58:29.033856256
min,2023-09-12 00:00:00,1.000000,1.000000,9.341190e+03,2015-01-01 00:00:00
25%,2024-03-17 00:00:00,1.000000,1.000000,1.162795e+06,2018-04-20 12:00:00
50%,2024-09-18 00:00:00,72.101700,72.101700,1.641946e+06,2021-11-05 00:00:00
75%,2025-03-20 00:00:00,80.276450,80.276450,2.235659e+06,2024-02-29 00:00:00
max,2025-09-11 00:00:00,109.968400,109.968400,2.936329e+06,2026-12-01 00:00:00
std,NaN,40.251934,40.251934,7.792754e+05,NaN

In [136]:
df['transactiontype']=df['transactiontype'].replace({'CREDIT':'Credit'})
df['transactiontype'].unique()

array(['Debit', 'Refund', 'Credit', 'debit'], dtype=object)

In [137]:
## the groupby data according to transsacction types
df.groupby('transactiontype')['amount'].agg(
    ['count','sum','mean','max','min'])

                 count         sum       mean       max  min
transactiontype
Credit            1983  91527.5847  46.156119  109.9583  1.0
Debit             2015  93452.1444  46.378235  109.9032  1.0
Refund             979  44968.3924  45.932985  109.7276  1.0
debit             1078  50703.8285  47.035091  109.9684  1.0

In [138]:
## groupby data according to categories
df.groupby('category')['amount'].agg(
    ['count','sum','mean','max','min'])

               count         sum       mean       max  min
category
Automotive       612  27914.1654  45.611381  109.7276  1.0
Clothing         582  26576.5641  45.664199  109.7041  1.0
Dining           639  30880.5938  48.326438  109.9583  1.0
Education        640  29902.9445  46.723351  109.9203  1.0
Electronics      626  27745.9957  44.322677  109.9684  1.0
Entertainment    594  26348.6166  44.357940  109.5771  1.0
Groceries        642  29538.2363  46.009714  109.0119  1.0
Health           565  26783.2974  47.404066  109.8633  1.0
Travel           572  26613.9062  46.527808  109.9160  1.0
Utilities        583  28347.6300  48.623722  109.8403  1.0

In [139]:
## group by based of country and sort of sum
df.groupby('country')['amount'].agg(
    ['count', 'sum', 'mean']
).sort_values('sum', ascending=False)

           count         sum       mean
country
UK          1083  49154.0741  45.386957
Australia   1019  48839.2907  47.928646
Canada      1035  47866.7644  46.248082
India        967  45362.5759  46.910627
USA          989  44798.2116  45.296473
UAE          962  44631.0333  46.394006

In [140]:
## the groupby based on currency 
df.groupby('currency')['amount'].agg(
     ['count','sum','mean','max','min'])

          count          sum       mean       max      min
currency
AED         979   19584.7220  20.004823   72.0930  18.0010
GBP        1024  102271.5224  99.874534  109.9684  90.0011
INR        2029    2029.0000   1.000000    1.0000   1.0000
USD        2023  156766.7056  77.492193   82.9964  21.5387

In [141]:
## the groupby based on fraud
df.groupby('isfraud')['amount'].agg(
     ['count','sum','mean','max','min']).sort_values('count', ascending=False)

         count          sum       mean       max  min
isfraud
No        5992  277808.6676  46.363262  109.9684  1.0
Yes         63    2843.2824  45.131467  104.9632  1.0

In [142]:
## make the pivot table
#categories and transaction based
pd.pivot_table(
                df,
               values='amount',
               index='category',
               columns='transactiontype',
               aggfunc='sum',
               fill_value=0
)

transactiontype      Credit       Debit     Refund      debit
category
Automotive        9062.4147   9525.4575  4687.5734  4638.7198
Clothing          8712.0487   8095.2376  5255.5547  4513.7231
Dining            9938.1179  10568.2673  5400.5791  4973.6295
Education         9532.5905   9763.0980  4414.8285  6192.4275
Electronics      11187.6541   8209.9025  3698.8856  4649.5535
Entertainment     7960.0969   9312.7670  3282.0263  5793.7264
Groceries         8332.8665  10608.2508  5426.7349  5170.3841
Health            9307.1423   8804.8112  3963.1699  4708.1740
Travel            8723.8768   9427.2779  3602.2991  4860.4524
Utilities         8770.7763   9137.0746  5236.7409  5203.0382

In [143]:
## the currency based country pivot tables
pd.pivot_table(
    df,
    values='amount',
    index='country',
    columns='currency',
    aggfunc=['sum','mean'],
    fill_value=0
)

                 sum                                      mean              \
currency         AED         GBP    INR         USD        AED         GBP
country
Australia  3225.7760  18127.5598  326.0  27159.9549  19.912198   99.601977
Canada     3303.1689  17474.3348  351.0  26738.2607  20.019205   99.853342
India      3249.0931  17109.0364  315.0  24689.4464  19.933087  100.641391
UAE        3121.2439  16048.6075  318.0  25143.1819  19.880534   99.680792
UK         3550.8072  16898.8702  372.0  28332.3967  20.406938   98.823802
USA        3134.6329  16613.1137  347.0  24703.4650  19.839449  100.685538


currency   INR        USD
country
Australia  1.0  77.822220
Canada     1.0  77.727502
India      1.0  77.396384
UAE        1.0  77.126325
UK         1.0  77.410920
USA        1.0  77.440329

In [144]:
## the fraud based transaction of pivot tables
pd.pivot_table(
    df,
    values='amount',
    index='transactiontype',
    columns='isfraud',
    aggfunc=['count','sum'],
    fill_value=0)

                count             sum
isfraud            No Yes          No        Yes
transactiontype
Credit           1958  25  90448.7244  1078.8603
Debit            1996  19  92626.1511   825.9933
Refund            970   9  44417.2634   551.1290
debit            1068  10  50316.5287   387.2998

In [145]:
## save the clean data
df.to_csv(
    "C:/Users/HP Core i5 10th Gen/Downloads//Finance_Ecommerce_clean_csv.csv",
    index=False
)